

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: Destemido_007
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: Twitter
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    container_name: fastapi_mysql_api
    restart: on-failure
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db:3306/Twitter
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src

volumes:
  mysql_data:
